# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Supermodel < Formula
  desc "Give your AI coding agent a map of your codebase"
  homepage "https://supermodeltools.com"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/supermodeltools/cli/releases/download/v0.3.0/supermodel_darwin_amd64.tar.gz"
      sha256 "912532c788191b69a20f09cfa633535a65b796ca85900475b22248e25cc5f7b9"

      define_method(:install) do
        bin.install "supermodel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/supermodeltools/cli/releases/download/v0.3.0/supermodel_darwin_arm64.tar.gz"
      sha256 "e76675741d5e8301e7e362a6fb1b4ce88e21a620bc2919baa5f47b1bfcb8ec93"

      define_method(:install) do
        bin.install "supermodel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/supermodeltools/cli/releases/download/v0.3.0/supermodel_linux_amd64.tar.gz"
      sha256 "83bd6992d0868d6b4156e6888c5bef279ef161ac6ace550393e09e2d2d3ce060"
      define_method(:install) do
        bin.install "supermodel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/supermodeltools/cli/releases/download/v0.3.0/supermodel_linux_arm64.tar.gz"
      sha256 "cd9b6477a7bd893615c970b2ff0624d6458e383b83df100f329da29e497167da"
      define_method(:install) do
        bin.install "supermodel"
      end
    end
  end

  test do
    system "#{bin}/supermodel", "version"
  end
end
