# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Supermodel < Formula
  desc "Give your AI coding agent a map of your codebase"
  homepage "https://supermodeltools.com"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/supermodeltools/cli/releases/download/v0.4.0/supermodel_darwin_amd64.tar.gz"
      sha256 "475b6cc01d6043c0c71a52bba5e47c961c81ca2760dc9b0ff916a5d3dfe5867c"

      define_method(:install) do
        bin.install "supermodel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/supermodeltools/cli/releases/download/v0.4.0/supermodel_darwin_arm64.tar.gz"
      sha256 "0da51f6f6ba35bd59cefffed75ba27e436ee991cc2ee94702c8d421c7d5f951e"

      define_method(:install) do
        bin.install "supermodel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/supermodeltools/cli/releases/download/v0.4.0/supermodel_linux_amd64.tar.gz"
      sha256 "ae4e95c0cd66b15377eb8ad01554c1bc8b44858a77dea6917e12e71255cf4e3e"
      define_method(:install) do
        bin.install "supermodel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/supermodeltools/cli/releases/download/v0.4.0/supermodel_linux_arm64.tar.gz"
      sha256 "83eed374d6cec1d837efc20a76560345cc68fa967b135ce6f8936f34f6f26003"
      define_method(:install) do
        bin.install "supermodel"
      end
    end
  end

  test do
    system "#{bin}/supermodel", "version"
  end
end
