# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Supermodel < Formula
  desc "Give your AI coding agent a map of your codebase"
  homepage "https://supermodeltools.com"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/supermodeltools/cli/releases/download/v0.2.1/supermodel_darwin_amd64.tar.gz"
      sha256 "30af10c0550182d2a93098c75919f758731b1485ba44b1e450fc20624ef85e09"

      define_method(:install) do
        bin.install "supermodel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/supermodeltools/cli/releases/download/v0.2.1/supermodel_darwin_arm64.tar.gz"
      sha256 "94a5dfaace16612ccbebf271aa2e7cdafa855ef78ecadb7a384e717432b33f39"

      define_method(:install) do
        bin.install "supermodel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/supermodeltools/cli/releases/download/v0.2.1/supermodel_linux_amd64.tar.gz"
      sha256 "bf7b278b0e8d5e2a7aa29ed2fd933104d7164c1712fcee796683df39c520189b"
      define_method(:install) do
        bin.install "supermodel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/supermodeltools/cli/releases/download/v0.2.1/supermodel_linux_arm64.tar.gz"
      sha256 "51df435a765a573b8f24baf91638eb61f8f760b4dc500b0b3783f8557bd41a3f"
      define_method(:install) do
        bin.install "supermodel"
      end
    end
  end

  test do
    system "#{bin}/supermodel", "version"
  end
end
