package restore

import (
	"bytes"
	"fmt"
	"strings"
	gotmpl "text/template"
	"time"
	"unicode"
)

const maxCyclesToShow = 10

// DefaultMaxTokens is the default token budget for the rendered context bomb.
const DefaultMaxTokens = 2000

var rendererTmpl = gotmpl.Must(
	gotmpl.New("context_bomb").Funcs(gotmpl.FuncMap{
		"join":         strings.Join,
		"languageList": func(langs []string) string { return strings.Join(langs, ", ") },
		"add1":         func(i int) int { return i + 1 },
		"blockquote": func(s string) string {
			s = strings.TrimRight(s, "\r\n")
			return strings.ReplaceAll(s, "\n", "\n> ")
		},
	}).Parse(contextBombTmpl),
)

const contextBombTmpl = `# Supermodel Context — {{.ProjectName}}

> Restored by ` + "`supermodel restore`" + ` at {{.Timestamp}}{{if .LocalMode}} | local mode (run ` + "`supermodel login`" + ` for AI-powered features){{end}}{{if .Stale}} | ⚠️ STALE: last updated {{.StaleDuration}}{{end}}
{{- if .Graph.Stats.CircularDependencyCycles}}
> ⚠️ {{.Graph.Stats.CircularDependencyCycles}} circular dependency {{if eq .Graph.Stats.CircularDependencyCycles 1}}cycle{{else}}cycles{{end}} detected{{range .CappedCycles}}
> - {{join .Cycle " → "}}{{end}}{{if .ExtraCycles}}
> ... and {{.ExtraCycles}} more{{end}}
{{- end}}
{{- if and (not .LocalMode) (not .Graph.CircularDepsAnalyzed)}}
> ⚠️ Circular dependency analysis unavailable
{{- end}}

## Project Overview

**Name:** {{.Graph.Name}}
**Language:** {{.Graph.Language}}{{if .Graph.Framework}}
**Framework:** {{.Graph.Framework}}{{end}}{{if .Graph.Description}}
**Description:** {{.Graph.Description}}{{end}}
**Codebase:** {{.Graph.Stats.TotalFiles}} files · {{.Graph.Stats.TotalFunctions}} functions
{{- if .Graph.Stats.Languages}}

**Languages:** {{languageList .Graph.Stats.Languages}}{{end}}{{if .Graph.ExternalDeps}}
**Tech stack:** {{join .Graph.ExternalDeps ", "}}{{end}}{{if .Graph.CriticalFiles}}
## Critical Files
{{range $i, $f := .Graph.CriticalFiles}}{{add1 $i}}. {{$f.Path}}{{if $f.RelationshipCount}} — {{$f.RelationshipCount}} relationships{{end}}
{{end}}{{end}}
## Domain Map
{{range .Graph.Domains}}
### {{.Name}}
{{.Description}}
{{if .KeyFiles}}**Key files:** {{join .KeyFiles ", "}}
{{end}}{{if .Responsibilities}}**Responsibilities:**
{{range .Responsibilities}}- {{.}}
{{end}}{{end}}{{if .Subdomains}}**Subdomains:**
{{range .Subdomains}}- {{.Name}}{{if .Description}}: {{.Description}}{{end}}
{{end}}{{end}}{{if .DependsOn}}**Depends on:** {{join .DependsOn ", "}}
{{end}}{{end}}{{- if .ClaudeMD}}
## Project Instructions (CLAUDE.md)

{{.ClaudeMD}}
{{- end}}
---
*Generated by [supermodel restore](https://supermodeltools.com)*`

// RenderOptions controls the context bomb output.
type RenderOptions struct {
	// MaxTokens is the token budget. Defaults to DefaultMaxTokens when zero.
	MaxTokens int
	// Stale indicates the graph data is older than the TTL.
	Stale   bool
	StaleAt *time.Time
	// ClaudeMD is the raw content of CLAUDE.md in the project root (may be "").
	ClaudeMD string
	// LocalMode causes an informational banner to be shown (no API key used).
	LocalMode bool
}

// Render produces the context bomb Markdown, respecting the token budget.
// Returns the rendered text, estimated token count, and any template error.
func Render(graph *ProjectGraph, projectName string, opts RenderOptions) (output string, tokens int, err error) {
	if opts.MaxTokens <= 0 {
		opts.MaxTokens = DefaultMaxTokens
	}

	now := time.Now().UTC()
	staleDuration := ""
	if opts.Stale && opts.StaleAt != nil {
		staleDuration = humanDuration(now.Sub(*opts.StaleAt))
	}

	cappedCycles := graph.Cycles
	extraCycles := 0
	if len(graph.Cycles) > maxCyclesToShow {
		cappedCycles = graph.Cycles[:maxCyclesToShow]
		extraCycles = len(graph.Cycles) - maxCyclesToShow
	}

	data := struct {
		ProjectName   string
		Timestamp     string
		Graph         *ProjectGraph
		CappedCycles  []CircularDependencyCycle
		ExtraCycles   int
		Stale         bool
		StaleDuration string
		ClaudeMD      string
		LocalMode     bool
	}{
		ProjectName:   projectName,
		Timestamp:     now.Format("2006-01-02 15:04:05 UTC"),
		Graph:         graph,
		CappedCycles:  cappedCycles,
		ExtraCycles:   extraCycles,
		Stale:         opts.Stale,
		StaleDuration: staleDuration,
		ClaudeMD:      opts.ClaudeMD,
		LocalMode:     opts.LocalMode,
	}

	var full bytes.Buffer
	if err := rendererTmpl.Execute(&full, data); err != nil {
		return "", 0, fmt.Errorf("rendering template: %w", err)
	}

	output = full.String()
	tokens = CountTokens(output)
	if tokens <= opts.MaxTokens {
		return output, tokens, nil
	}
	return truncateToTokenBudget(graph, projectName, opts)
}

// truncateToTokenBudget progressively drops lower-priority content to fit.
func truncateToTokenBudget(graph *ProjectGraph, projectName string, opts RenderOptions) (output string, tokens int, err error) { //nolint:gocyclo // progressive truncation strategy; splitting would obscure priority ordering
	now := time.Now().UTC()
	staleDuration := ""
	if opts.Stale && opts.StaleAt != nil {
		staleDuration = humanDuration(now.Sub(*opts.StaleAt))
	}

	var hdr strings.Builder
	fmt.Fprintf(&hdr, "# Supermodel Context — %s\n\n", projectName)
	banner := fmt.Sprintf("> Restored by `supermodel restore` at %s", now.Format("2006-01-02 15:04:05 UTC"))
	if opts.LocalMode {
		banner += " | local mode (run `supermodel login` for AI-powered features)"
	}
	if opts.Stale && staleDuration != "" {
		banner += fmt.Sprintf(" | ⚠️ STALE: last updated %s", staleDuration)
	}
	hdr.WriteString(banner + "\n")
	if graph.Stats.CircularDependencyCycles > 0 {
		label := "cycles"
		if graph.Stats.CircularDependencyCycles == 1 {
			label = "cycle"
		}
		fmt.Fprintf(&hdr, "> ⚠️ %d circular dependency %s detected\n", graph.Stats.CircularDependencyCycles, label)
	}
	fmt.Fprintf(&hdr,
		"\n**Language:** %s · **Files:** %d · **Functions:** %d",
		graph.Language, graph.Stats.TotalFiles, graph.Stats.TotalFunctions,
	)
	required := hdr.String()

	reqTokens := CountTokens(required)
	if reqTokens > opts.MaxTokens {
		fb := "# Supermodel Context\n\n(Budget too small; increase --max-tokens)"
		return fb, CountTokens(fb), nil
	}
	remaining := opts.MaxTokens - reqTokens

	var sb strings.Builder
	sb.WriteString(required)

	if len(graph.CriticalFiles) > 0 {
		header := "\n\n## Critical Files\n"
		if ht := CountTokens(header); ht <= remaining {
			sb.WriteString(header)
			remaining -= ht
			for i, f := range graph.CriticalFiles {
				var line string
				if f.RelationshipCount > 0 {
					line = fmt.Sprintf("%d. %s — %d relationships\n", i+1, f.Path, f.RelationshipCount)
				} else {
					line = fmt.Sprintf("%d. %s\n", i+1, f.Path)
				}
				lt := CountTokens(line)
				if lt > remaining {
					break
				}
				sb.WriteString(line)
				remaining -= lt
			}
		}
	}

	header := "\n\n## Domain Map\n"
	if ht := CountTokens(header); ht <= remaining {
		sectionBudget := remaining - ht
		var sections []string
		for i := range graph.Domains {
			s := buildDomainSection(&graph.Domains[i])
			if st := CountTokens(s); st <= sectionBudget {
				sections = append(sections, s)
				sectionBudget -= st
			}
			if sectionBudget < 50 {
				break
			}
		}
		if len(sections) > 0 {
			sb.WriteString(header)
			remaining = sectionBudget
			for _, s := range sections {
				sb.WriteString(s)
			}
		}
	}

	if opts.ClaudeMD != "" {
		header := "\n\n## Project Instructions (CLAUDE.md)\n\n"
		ht := CountTokens(header)
		ct := CountTokens(opts.ClaudeMD)
		if ht+ct <= remaining {
			sb.WriteString(header)
			sb.WriteString(opts.ClaudeMD)
			sb.WriteString("\n")
			remaining -= ht + ct + 1
		}
	}

	footer := "\n\n---\n*Generated by supermodel restore (budget-truncated)*"
	if CountTokens(footer) <= remaining {
		sb.WriteString(footer)
	}

	result := sb.String()
	return result, CountTokens(result), nil
}

func buildDomainSection(d *Domain) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "\n### %s\n%s\n", d.Name, d.Description)
	if len(d.KeyFiles) > 0 {
		fmt.Fprintf(&sb, "**Key files:** %s\n", strings.Join(d.KeyFiles, ", "))
	}
	if len(d.Responsibilities) > 0 {
		sb.WriteString("**Responsibilities:**\n")
		for _, r := range d.Responsibilities {
			fmt.Fprintf(&sb, "- %s\n", r)
		}
	}
	if len(d.Subdomains) > 0 {
		sb.WriteString("**Subdomains:**\n")
		for _, s := range d.Subdomains {
			if s.Description != "" {
				fmt.Fprintf(&sb, "- %s: %s\n", s.Name, s.Description)
			} else {
				fmt.Fprintf(&sb, "- %s\n", s.Name)
			}
		}
	}
	if len(d.DependsOn) > 0 {
		fmt.Fprintf(&sb, "**Depends on:** %s\n", strings.Join(d.DependsOn, ", "))
	}
	return sb.String()
}

// CountTokens estimates the LLM token count of text using max(chars/4, words*4/3).
func CountTokens(text string) int {
	words := 0
	inWord := false
	for _, r := range text {
		if unicode.IsSpace(r) {
			inWord = false
		} else if !inWord {
			words++
			inWord = true
		}
	}
	charEstimate := len(text) / 4
	wordEstimate := words * 100 / 75
	if charEstimate > wordEstimate {
		return charEstimate
	}
	return wordEstimate
}

func humanDuration(d time.Duration) string {
	if d < time.Minute {
		return fmt.Sprintf("%d seconds", int(d.Seconds()))
	}
	if d < time.Hour {
		return fmt.Sprintf("%d minutes", int(d.Minutes()))
	}
	if d < 24*time.Hour {
		return fmt.Sprintf("%.1f hours", d.Hours())
	}
	return fmt.Sprintf("%.1f days", d.Hours()/24)
}
